[versions]
zalandoProblem = { strictly = '0.26.0' }
lambdaLog4j = { strictly = '1.2.0' }
guava = { strictly = '31.0.1-jre' }
awsSdk = { strictly = '1.12.112' }
awsSdk2 = { strictly = '2.17.24' }
awsLambdaEvents = { strictly = '3.2.0' }
awsLambdaCore = { strictly = '1.2.1' }
mockito = { strictly = '4.0.0' }
httpmime = { strictly = '4.5.13' }
jackson = { strictly = '2.12.4' }
hamcrest = { strictly = '2.2' }
apacheCommons = { strictly = '3.12.0' }
commonsValidator = { strictly = '1.7' }
javaFaker = { strictly = '1.0.2' }
jupiter = { strictly = '5.8.1' }
awsIon = { strictly = '1.5.1' }
hamcrestOptional = { strictly = '2.0.0' }

[libraries]
zalando = { group = 'org.zalando', name = 'problem', version.ref = 'zalandoProblem' }
lambda-log4j = { group = 'com.amazonaws', name = 'aws-lambda-java-log4j2', version.ref = 'lambdaLog4j' }
guava = { group = 'com.google.guava', name = 'guava', version.ref = 'guava' }

aws-sdk-sts = { group = 'com.amazonaws', name = 'aws-java-sdk-sts', version.ref = 'awsSdk' }
aws-sdk-core = { group = 'com.amazonaws', name = 'aws-java-sdk-core', version.ref = 'awsSdk' }
aws-sdk-dynamo = { group = 'com.amazonaws', name = 'aws-java-sdk-dynamodb', version.ref = 'awsSdk' }
aws-lambda-events = { group = 'com.amazonaws', name = 'aws-lambda-java-events', version.ref = 'awsLambdaEvents' }
aws-lambda-core = { group = 'com.amazonaws', name = 'aws-lambda-java-core', version.ref = 'awsLambdaCore' }
aws-sdk-secrets = { group = 'com.amazonaws', name = 'aws-java-sdk-secretsmanager', version.ref = 'awsSdk' }

aws-sdk2-core = { group = 'software.amazon.awssdk', name = 'sdk-core', version.ref = 'awsSdk2' }
aws-ion = { group = 'software.amazon.ion', name = 'ion-java', version.ref = 'awsIon' }
aws-sdk-s3 = { group = 'software.amazon.awssdk', name = 's3', version.ref = 'awsSdk2' }
aws-sdk-eventbridge = { group = 'software.amazon.awssdk', name = 'eventbridge', version.ref = 'awsSdk2' }
aws-http-client-spi = { group = 'software.amazon.awssdk', name = 'http-client-spi', version = 'awsSdk2' }
aws-apache-client = { group = 'software.amazon.awssdk', name = 'apache-client', version.ref = 'awsSdk2' }

httpmime = { group = 'org.apache.httpcomponents', name = 'httpmime', version.ref = 'httpmime' }

jackson-datatype = { group = 'com.fasterxml.jackson.datatype', name = 'jackson-datatype-jdk8', version.ref = 'jackson' }
jackson-databind = { group = 'com.fasterxml.jackson.core', name = 'jackson-databind', version.ref = 'jackson' }
jackson-module-parameter-names = { group = 'com.fasterxml.jackson.module', name = 'jackson-module-parameter-names', version.ref = 'jackson' }

commons-lang = { group = 'org.apache.commons', name = 'commons-lang3', version.ref = 'apacheCommons' }
commons-validator = { group = 'commons-validator', name = 'commons-validator', version.ref = 'commonsValidator' }

junit-jupiter = { group = 'org.junit.jupiter', name = 'junit-jupiter', version.ref = 'jupiter' }
hamcrest = { group = 'org.hamcrest', name = 'hamcrest', version.ref = 'hamcrest' }
javaFaker = { group = 'com.github.javafaker', name = 'javafaker', version.ref = 'javaFaker' }
mockito-core = { group = 'org.mockito', name = 'mockito-core', version.ref = 'mockito' }
hamcrest-optional = { group = 'com.github.npathai', name = 'hamcrest-optional', version.ref = 'hamcrestOptional' }


[bundles]
testing = ['mockito-core', 'hamcrest', 'junit-jupiter', 'javaFaker', 'hamcrest-optional']
jackson = ['jackson-datatype', 'jackson-databind', 'jackson-module-parameter-names']