[versions]

zalandoProblem = { strictly = '0.27.1' }
lambdaLog4j = { strictly = '1.6.0' }
guava = { strictly = '33.3.0-jre' }
awsSdk = { strictly = '1.12.772' }
awsSdk2 = { strictly = '2.27.24' }
awsLambdaEvents = { strictly = '3.13.0' }
awsLambdaCore = { strictly = '1.2.3' }
mockito = { strictly = '5.13.0' }
httpmime = { strictly = '4.5.14' }
jackson = { strictly = '2.17.2' }
hamcrest = { strictly = '3.0' }
apacheCommons = { require = '3.17.0' }
commonsValidator = { strictly = '1.9.0' }
jupiter = { strictly = '5.11.0' }
awsIon = { strictly = '1.11.9' }
hamcrestOptional = { strictly = '2.0.0' }
log4j = { strictly = '2.24.0' }
#wiremock 3.0.2 has multiple versions of  slf4j
slf4j = { require = '2.0.16' }
apiGuardian = { strictly = '1.1.2' }
wiremock = { strictly = '3.9.1' }
datafaker = { strictly = '2.3.1' }
com-auth0-jwt = { strictly = '4.4.0' }
apacheHttpClient = { strictly = '5.3.1' }

[libraries]
zalando = { group = 'org.zalando', name = 'problem', version.ref = 'zalandoProblem' }

guava = { group = 'com.google.guava', name = 'guava', version.ref = 'guava' }

aws-sdk-dynamo = { group = 'com.amazonaws', name = 'aws-java-sdk-dynamodb', version.ref = 'awsSdk' }
aws-java-sdk-core = { group = 'com.amazonaws', name = 'aws-java-sdk-core', version.ref = 'awsSdk' }
aws-lambda-events = { group = 'com.amazonaws', name = 'aws-lambda-java-events', version.ref = 'awsLambdaEvents' }
aws-lambda-core = { group = 'com.amazonaws', name = 'aws-lambda-java-core', version.ref = 'awsLambdaCore' }

aws-sdk2-core = { group = 'software.amazon.awssdk', name = 'sdk-core', version.ref = 'awsSdk2' }
aws-sdk2-secrets = { group = 'software.amazon.awssdk', name = 'secretsmanager', version.ref = 'awsSdk2' }
aws-sdk2-s3 = { group = 'software.amazon.awssdk', name = 's3', version.ref = 'awsSdk2' }
aws-sdk2-eventbridge = { group = 'software.amazon.awssdk', name = 'eventbridge', version.ref = 'awsSdk2' }
aws-sdk2-urlconnection = { group = 'software.amazon.awssdk', name = 'url-connection-client', version.ref = 'awsSdk2' }
aws-sdk2-dynamo = { group = 'software.amazon.awssdk', name = 'dynamodb', version.ref = 'awsSdk2' }
aws-sdk2-cognitoidp = { group = 'software.amazon.awssdk', name = 'cognitoidentityprovider', version.ref = 'awsSdk2' }
aws-sdk2-firehose = { group = 'software.amazon.awssdk', name = 'firehose', version.ref = 'awsSdk2' }

aws-http-client-spi = { group = 'software.amazon.awssdk', name = 'http-client-spi', version = 'awsSdk2' }
aws-apache-client = { group = 'software.amazon.awssdk', name = 'apache-client', version.ref = 'awsSdk2' }
aws-ion = { group = 'com.amazon.ion', name = 'ion-java', version.ref = 'awsIon' }

httpmime = { group = 'org.apache.httpcomponents', name = 'httpmime', version.ref = 'httpmime' }

jackson-core = { group = 'com.fasterxml.jackson.core', name = 'jackson-core', version.ref = 'jackson' }
jackson-datatype-jdk8 = { group = 'com.fasterxml.jackson.datatype', name = 'jackson-datatype-jdk8', version.ref = 'jackson' }
jackson-datatype-jsr310 = { group = 'com.fasterxml.jackson.datatype', name = 'jackson-datatype-jsr310', version.ref = 'jackson' }
jackson-databind = { group = 'com.fasterxml.jackson.core', name = 'jackson-databind', version.ref = 'jackson' }
jackson-annotations = { group = 'com.fasterxml.jackson.core', name = 'jackson-annotations', version.ref = 'jackson' }
jackson-module-parameter-names = { group = 'com.fasterxml.jackson.module', name = 'jackson-module-parameter-names', version.ref = 'jackson' }
jackson-datatype-problem = { group = 'org.zalando', name = 'jackson-datatype-problem', version.ref = 'zalandoProblem' }
jackson-dataformat-xml = { group = 'com.fasterxml.jackson.dataformat', name = 'jackson-dataformat-xml', version.ref = 'jackson' }


jackson-jr-objects = { group = 'com.fasterxml.jackson.jr', name = 'jackson-jr-objects', version.ref = 'jackson' }
jackson-jr-stree = { group = 'com.fasterxml.jackson.jr', name = 'jackson-jr-stree', version.ref = 'jackson' }
jackson-jr-annotations = { group = 'com.fasterxml.jackson.jr', name = 'jackson-jr-annotation-support', version.ref = 'jackson' }

commons-lang = { group = 'org.apache.commons', name = 'commons-lang3', version.ref = 'apacheCommons' }
commons-validator = { group = 'commons-validator', name = 'commons-validator', version.ref = 'commonsValidator' }


log4j-core = { group = 'org.apache.logging.log4j', name = 'log4j-core', version.ref = 'log4j' }
log4j-api = { group = 'org.apache.logging.log4j', name = 'log4j-api', version.ref = 'log4j' }
log4j-slf4j-impl = { group = 'org.apache.logging.log4j', name = 'log4j-slf4j2-impl', version.ref = 'log4j' }
slf4j-api = { group = 'org.slf4j', name = 'slf4j-api', version.ref = 'slf4j' }
lambda-log4j = { group = 'com.amazonaws', name = 'aws-lambda-java-log4j2', version.ref = 'lambdaLog4j' }

junit-jupiter = { group = 'org.junit.jupiter', name = 'junit-jupiter', version.ref = 'jupiter' }
junit-jupiter-api = { group = 'org.junit.jupiter', name = 'junit-jupiter-api', version.ref = 'jupiter' }
junit-jupiter-params = { group = 'org.junit.jupiter', name = 'junit-jupiter-params', version.ref = 'jupiter' }
junit-jupiter-engine = { group = 'org.junit.jupiter', name = 'junit-jupiter-engine', version.ref = 'jupiter' }
hamcrest = { group = 'org.hamcrest', name = 'hamcrest', version.ref = 'hamcrest' }
hamcrest-core = { group = 'org.hamcrest', name = 'hamcrest-core', version.ref = 'hamcrest' }
mockito-core = { group = 'org.mockito', name = 'mockito-core', version.ref = 'mockito' }
hamcrest-optional = { group = 'com.github.npathai', name = 'hamcrest-optional', version.ref = 'hamcrestOptional' }
datafaker = { group = 'net.datafaker', name = 'datafaker', version.ref = 'datafaker' }
httpclient5 = { group = 'org.apache.httpcomponents.client5', name = 'httpclient5', version.ref = 'apacheHttpClient' }

apiguardian = { group = 'org.apiguardian', name = 'apiguardian-api', version.ref = 'apiGuardian' }
wiremock = { group = 'org.wiremock', name = 'wiremock', version.ref = 'wiremock' }


com-auth0-jwt = { group = 'com.auth0', name = 'java-jwt', version.ref = 'com-auth0-jwt' }

[bundles]
testing = ['mockito-core', 'hamcrest', 'hamcrest-core', 'junit-jupiter', 'junit-jupiter-api',
    'junit-jupiter-params', 'junit-jupiter-engine', 'hamcrest-optional', 'commons-lang', 'datafaker']
jackson = ['jackson-core', 'jackson-datatype-jdk8', 'jackson-datatype-jsr310', 'jackson-databind',
    'jackson-annotations', 'jackson-module-parameter-names', 'jackson-datatype-problem', 'jackson-dataformat-xml']
jacksonjr = ['jackson-jr-objects', 'jackson-jr-annotations']
logging = ['log4j-core', 'log4j-api', 'log4j-slf4j-impl', 'slf4j-api', 'lambda-log4j']

