# IMPORTANT: This is a published version catalog, used by other NVA repositories.
# Renaming a component (library, plugin, or bundle) or upgrading major versions of dependencies
# is a breaking change and should be reflected in our version number.
[versions]
apacheCommons = { require = '3.17.0' }
apacheHttpClient = { strictly = '5.5' }
awsIon = { strictly = '1.11.10' }
awsLambdaCore = { strictly = '1.3.0' }
awsLambdaEvents = { strictly = '3.16.0' }
awsSdk = { strictly = '1.12.787' }
awsSdk2 = { strictly = '2.31.77' }
com-auth0-jwt = { strictly = '4.5.0' }
com-auth0-jwks = { strictly = '0.22.2' }
commonsValidator = { strictly = '1.10.0' }
datafaker = { strictly = '2.4.3' }
guava = { strictly = '33.4.8-jre' }
hamcrest = { strictly = '3.0' }
jackson = { strictly = '2.19.1' }
jupiter = { strictly = '5.13.3' }
jupiterPlatform = { strictly = '1.13.3' } # Keep minor & patch version in sync with `jupiter`
lambdaLog4j = { strictly = '1.6.0' }
log4j = { strictly = '2.25.0' }
mockito = { strictly = '5.18.0' }
slf4j = { strictly = '2.0.17' }
wiremock = { strictly = '4.0.0-beta.14' }
zalandoProblem = { strictly = '0.27.1' }

[libraries]
# IMPORTANT: Renaming a library is a breaking change
aws-apache-client = { group = 'software.amazon.awssdk', name = 'apache-client', version.ref = 'awsSdk2' }
aws-ion = { group = 'com.amazon.ion', name = 'ion-java', version.ref = 'awsIon' }
aws-java-sdk-core = { group = 'com.amazonaws', name = 'aws-java-sdk-core', version.ref = 'awsSdk' }
aws-lambda-core = { group = 'com.amazonaws', name = 'aws-lambda-java-core', version.ref = 'awsLambdaCore' }
aws-lambda-events = { group = 'com.amazonaws', name = 'aws-lambda-java-events', version.ref = 'awsLambdaEvents' }
aws-sdk-dynamo = { group = 'com.amazonaws', name = 'aws-java-sdk-dynamodb', version.ref = 'awsSdk' }
aws-sdk2-core = { group = 'software.amazon.awssdk', name = 'sdk-core', version.ref = 'awsSdk2' }
aws-sdk2-dynamo = { group = 'software.amazon.awssdk', name = 'dynamodb', version.ref = 'awsSdk2' }
aws-sdk2-eventbridge = { group = 'software.amazon.awssdk', name = 'eventbridge', version.ref = 'awsSdk2' }
aws-sdk2-firehose = { group = 'software.amazon.awssdk', name = 'firehose', version.ref = 'awsSdk2' }
aws-sdk2-s3 = { group = 'software.amazon.awssdk', name = 's3', version.ref = 'awsSdk2' }
aws-sdk2-secrets = { group = 'software.amazon.awssdk', name = 'secretsmanager', version.ref = 'awsSdk2' }
aws-sdk2-urlconnection = { group = 'software.amazon.awssdk', name = 'url-connection-client', version.ref = 'awsSdk2' }

com-auth0-jwks = { group = 'com.auth0', name =  'jwks-rsa', version.ref= 'com-auth0-jwks' }
com-auth0-jwt = { group = 'com.auth0', name = 'java-jwt', version.ref = 'com-auth0-jwt' }
commons-lang = { group = 'org.apache.commons', name = 'commons-lang3', version.ref = 'apacheCommons' }
commons-validator = { group = 'commons-validator', name = 'commons-validator', version.ref = 'commonsValidator' }
guava = { group = 'com.google.guava', name = 'guava', version.ref = 'guava' }

jackson-annotations = { group = 'com.fasterxml.jackson.core', name = 'jackson-annotations', version.ref = 'jackson' }
jackson-core = { group = 'com.fasterxml.jackson.core', name = 'jackson-core', version.ref = 'jackson' }
jackson-databind = { group = 'com.fasterxml.jackson.core', name = 'jackson-databind', version.ref = 'jackson' }
jackson-dataformat-xml = { group = 'com.fasterxml.jackson.dataformat', name = 'jackson-dataformat-xml', version.ref = 'jackson' }
jackson-datatype-jdk8 = { group = 'com.fasterxml.jackson.datatype', name = 'jackson-datatype-jdk8', version.ref = 'jackson' }
jackson-datatype-jsr310 = { group = 'com.fasterxml.jackson.datatype', name = 'jackson-datatype-jsr310', version.ref = 'jackson' }
jackson-datatype-problem = { group = 'org.zalando', name = 'jackson-datatype-problem', version.ref = 'zalandoProblem' }

jackson-jr-annotations = { group = 'com.fasterxml.jackson.jr', name = 'jackson-jr-annotation-support', version.ref = 'jackson' }
jackson-jr-objects = { group = 'com.fasterxml.jackson.jr', name = 'jackson-jr-objects', version.ref = 'jackson' }
jackson-module-parameter-names = { group = 'com.fasterxml.jackson.module', name = 'jackson-module-parameter-names', version.ref = 'jackson' }
zalando = { group = 'org.zalando', name = 'problem', version.ref = 'zalandoProblem' }

# Logging dependencies
lambda-log4j = { group = 'com.amazonaws', name = 'aws-lambda-java-log4j2', version.ref = 'lambdaLog4j' }
log4j-api = { group = 'org.apache.logging.log4j', name = 'log4j-api', version.ref = 'log4j' }
log4j-core = { group = 'org.apache.logging.log4j', name = 'log4j-core', version.ref = 'log4j' }
log4j-slf4j-impl = { group = 'org.apache.logging.log4j', name = 'log4j-slf4j2-impl', version.ref = 'log4j' }
slf4j-api = { group = 'org.slf4j', name = 'slf4j-api', version.ref = 'slf4j' }

# Test dependencies
datafaker = { group = 'net.datafaker', name = 'datafaker', version.ref = 'datafaker' }
hamcrest = { group = 'org.hamcrest', name = 'hamcrest', version.ref = 'hamcrest' }
hamcrest-core = { group = 'org.hamcrest', name = 'hamcrest-core', version.ref = 'hamcrest' }
httpclient5 = { group = 'org.apache.httpcomponents.client5', name = 'httpclient5', version.ref = 'apacheHttpClient' }
junit-jupiter = { group = 'org.junit.jupiter', name = 'junit-jupiter', version.ref = 'jupiter' }
junit-jupiter-api = { group = 'org.junit.jupiter', name = 'junit-jupiter-api', version.ref = 'jupiter' }
junit-jupiter-engine = { group = 'org.junit.jupiter', name = 'junit-jupiter-engine', version.ref = 'jupiter' }
junit-jupiter-params = { group = 'org.junit.jupiter', name = 'junit-jupiter-params', version.ref = 'jupiter' }
junit-platform-launcher = { group = 'org.junit.platform', name = 'junit-platform-launcher', version.ref = 'jupiterPlatform' }
mockito-core = { group = 'org.mockito', name = 'mockito-core', version.ref = 'mockito' }
wiremock = { group = 'org.wiremock', name = 'wiremock', version.ref = 'wiremock' }

[bundles]
# IMPORTANT: Renaming a bundle or removing elements from it is a breaking change
testing-junit = [
    'junit-jupiter',
    'junit-jupiter-api', 
    'junit-jupiter-engine',
    'junit-jupiter-params',
    'junit-platform-launcher'
]
testing-mockito = ['mockito-core']
testing-hamcrest = ['hamcrest', 'hamcrest-core']
jackson = [
    'jackson-annotations',
    'jackson-core',
    'jackson-databind',
    'jackson-dataformat-xml',
    'jackson-datatype-jdk8',
    'jackson-datatype-jsr310',
    'jackson-datatype-problem',
    'jackson-module-parameter-names'
]
jacksonjr = ['jackson-jr-objects', 'jackson-jr-annotations']
logging = [
    'lambda-log4j',
    'log4j-api',
    'log4j-core',
    'log4j-slf4j-impl',
    'slf4j-api'
]

